export const features = [
    //positive features
      {feature: "+syll", members: ['m','n','ŋ','ɹ','l']},
      {feature: "+cons", members: ['p','b','t','d','ɾ','k','g','ʔ','tʃ','dʒ','f','v','θ','ð','s','z','ʃ','ʒ','h','m','n','ŋ','ɹ','l']},
      {feature: "+son", members: ['m','n','ŋ','ɹ','l','w','j']},
      {feature: "+cor", members: ['t','d','ɾ','tʃ','dʒ','θ','ð','s','z','ʃ','ʒ','n','ɹ','l','j']},
      {feature: "+ant", members: ['p','b','t','d','ɾ','f','v','θ','ð','s','z','m','n','ɹ','l']},
      {feature: "+cont", members: ['f','v','θ','ð','s','z','ʃ','ʒ','h','ɹ','l','w','j']},
      {feature: "+nas", members: ['m','n','ŋ']},
      {feature: "+strid", members: ['tʃ','dʒ','f','v','s','z','ʃ','ʒ']},
      {feature: "+lat", members: ['l']},
      {feature: "+d.r", members: ['tʃ','dʒ']},
      {feature: "+voice", members: ['b','d','ɾ','g','ʔ','dʒ','v','ð','z','ʒ','m','n','ŋ','ɹ','l','w','j','e','i','u','o','a','ɑ','æ','ə','ɛ','ɪ','ɔ','ʊ','ʌ','y']},
    //negative features
      {feature: "-syll", members: ['p','b','t','d','ɾ','k','g','ʔ','tʃ','dʒ','f','v','θ','ð','s','z','ʃ','ʒ','h','w','j']},
      {feature: "-cons", members: ['w','j']},
      {feature: "-son", members: ['p','b','t','d','ɾ','k','g','ʔ','tʃ','dʒ','f','v','θ','ð','s','z','ʃ','ʒ','h']},
      {feature: "-cor", members: ['p','b','k','g','ʔ','f','v','h','m','ŋ','w']},
      {feature: "-ant", members: ['k','g','ʔ','tʃ','dʒ','ʃ','ʒ','h','ŋ','w','j']},
      {feature: "-cont", members: ['p','b','t','d','ɾ','k','g','ʔ','tʃ','dʒ','m','n','ŋ']},
      {feature: "-nas", members: ['p','b','t','d','ɾ','k','g','ʔ','tʃ','dʒ','f','v','θ','ð','s','z','ʃ','ʒ','h','ɹ','l','w','j']},
      {feature: "-strid", members: ['p','b','t','d','ɾ','k','g','ʔ','θ','ð','h','m','n','ŋ','ɹ','l','w','j']},
      {feature: "-lat", members: ['p','b','t','d','ɾ','k','g','ʔ','tʃ','dʒ','f','v','θ','ð','s','z','ʃ','ʒ','h','ɹ','m','n','ŋ','w','j']},
      {feature: "-d.r", members: ['p','b','t','d','ɾ','k','g','ʔ','f','v','θ','ð','s','z','ʃ','ʒ','h','ɹ','m','n','ŋ','w','j','l']},
      {feature: "-voice", members: ['p','t','k','ʔ','tʃ','f','θ','s','ʃ','h']},
    //positive vowel features
      {feature: "+high", members:['i','y','u','ɪ','ʊ']},
      {feature: "+low", members:['æ','ɑ','a']},
      {feature: "+front", members:['e','i','a','æ','ɛ','ɪ','y']},
      {feature: "+back", members:['u','ɑ','ɔ','ʊ','ʌ','o']},
      {feature: "+round", members:['u','ɔ','ʊ','o','y']},
      {feature: "+tense", members: ['e','i','u','a','ɑ','o']},
    // negative vowel features
      {feature: "-high", members:['e','a','ɑ','æ','ə','ɛ','ɔ','ʌ','o']},
      {feature: "-low", members:['e','i','u','ə','ɛ','ɪ','ɔ','ʊ','ʌ','o']},
      {feature: "-back", members:['e','i','a','æ','ə','ɛ','ɪ']},
      {feature: "-front", members:['u','ɑ','ə','ɔ','ʊ','ʌ','o']},
      {feature: "-round", members:['e','i','a','ɑ','æ','ə','ɛ','ɪ','ʌ']},
      {feature: "-tense", members:['æ','ə','ɛ','ɪ','ɔ','ʊ','ʌ']},
    // all symbols: ["m", "n", "ŋ", "ɹ", "l", "p", "b", "t", "d", "ɾ", "k", "g", "ʔ", "tʃ", "dʒ", "f", "v", "θ", "ð", "s", "z", "ʃ", "ʒ", "h", "w", "j", "e", "i", "u", "o", "a", "ɑ", "æ", "ə", "ɛ", "ɪ", "ɔ", "ʊ", "ʌ", "y" ]
]

export const places = [
    { c: 'm', p: '' },  
    { c: 'n', p: '' },
    { c: 'ŋ', p: '' },  
    { c: 'ɹ', p: '' },
    { c: 'l', p: '' },  
    { c: 'p', p: '' },
    { c: 'b', p: '' },  
    { c: 't', p: '' },
    { c: 'd', p: '' },  
    { c: 'ɾ', p: '' },
    { c: 'k', p: '' },  
    { c: 'g', p: '' },
    { c: 'ʔ', p: '' },  
    { c: 'tʃ', p: '' },
    { c: 'dʒ', p: '' }, 
    { c: 'f', p: '' },
    { c: 'v', p: '' },  
    { c: 'θ', p: '' },
    { c: 'ð', p: '' },  
    { c: 's', p: '' },
    { c: 'z', p: '' },  
    { c: 'ʃ', p: '' },
    { c: 'ʒ', p: '' },  
    { c: 'h', p: '' },
    { c: 'w', p: '' },  
    { c: 'j', p: '' },
    { c: 'e', p: '' },  
    { c: 'i', p: '' },
    { c: 'u', p: '' },  
    { c: 'o', p: '' },
    { c: 'a', p: '' },  
    { c: 'ɑ', p: '' },
    { c: 'æ', p: '' },  
    { c: 'ə', p: '' },
    { c: 'ɛ', p: '' },  
    { c: 'ɪ', p: '' },
    { c: 'ɔ', p: '' },  
    { c: 'ʊ', p: '' },
    { c: 'ʌ', p: '' },  
    { c: 'y', p: '' }
  ]